### ISSUE TITLE
Terrapin

### ISSUE THREAD

**Issue by phillw** [coderobe/VBiosFinder#23] opened 2019-11-22 18:58 UTC
Hello,

Unsure what i'm doing wrong here

./vbiosfinder extract '/home/phill/E1771IMS.70G' 
output will be stored in '/home/phill/VBiosFinder/tmp-vbiosfinder'
checking for ruby... yes

checking for innoextract... yes
checking for upx... yes
checking for 7z... yes
trying to extract ./E1771IMS.70G
extracting uefi data
trying to extract ./E1771IMS.70G
Cleaning up garbage
Traceback (most recent call last):
	12: from _init.rb:7:in `<main>'
	11: from /home/phill/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	10: from /home/phill/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 9: from /home/phill/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /home/phill/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 7: from /home/phill/VBiosFinder/src/cli.rb:36:in `extract'
	 6: from /home/phill/VBiosFinder/src/methods.rb:43:in `run'
	 5: from /home/phill/VBiosFinder/src/methods.rb:43:in `each'
	 4: from /home/phill/VBiosFinder/src/methods.rb:45:in `block in run'
	 3: from /home/phill/VBiosFinder/src/extraction.rb:8:in `attempt'
	 2: from /home/phill/VBiosFinder/src/extraction.rb:8:in `call'
	 1: from /home/phill/VBiosFinder/src/extract-uefi.rb:20:in `uefi'
/home/phill/VBiosFinder/vendor/bundle/ruby/2.5.0/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run': Terrapin::CommandNotFoundError (Terrapin::CommandNotFoundError)

**Comment by coderobe** [comment] 2019-11-22 20:05
You do not have `UEFIExtract` in your PATH, which is a requirement

**Comment by coderobe** [comment] 2021-02-14 21:43
closing as effective duplicate of https://github.com/coderobe/VBiosFinder/issues/11

**Closed by coderobe** 2021-02-14 21:43 UTC
